[project]
name = "cidiff-nb"
version = "1.0.0"
description = "Data analysis for the CiDiff paper."
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "plotnine>=0.14.5"
]